sonar.projectKey=webew_oc-projet-8
sonar.organization=webew

sonar.projectName=oc-projet-8
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# ✅ On analyse uniquement le code applicatif
sonar.sources=api/app

# ✅ On déclare les tests à part (important pour Sonar)
sonar.tests=api/tests

# ✅ Exclusions minimales (node_modules etc. inutiles ici mais ok si monorepo)
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/.venv/**,**/__pycache__/**,**/*.min.js,**/*.html,**/*.ipynb
